kind: Service
apiVersion: v1
metadata:
  name: ecosia-service
spec:
  selector:
    app: ecosia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosia-deployment
  labels:
    app: ecosia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecosia
  template:
    metadata:
      labels:
        app: ecosia
    spec:
      containers:
      - name: ecosia
        image: stanma/ecosia
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ecosia-ingress
spec:
  rules:
  - host: local.ecosia.org
    http:
      paths:
      - backend:
          serviceName: ecosia-service
          servicePort: 80